# Generated by Django 4.2.17 on 2025-01-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=100, unique=True)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
