# Generated by Django 4.2.17 on 2025-01-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reward',
            new_name='CatalogueItem',
        ),
    ]
