# Generated by Django 4.2.17 on 2025-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_reward_catalogueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='catalogueitem',
            name='image',
            field=models.ImageField(upload_to='media/reward_images/'),
        ),
    ]
