# Generated by Django 4.2.17 on 2025-02-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_redemption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogueitem",
            name="points_cost",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of points required to redeem this reward.",
            ),
        ),
        migrations.CreateModel(
            name="RedemptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="The quantity of this item redeemed."
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item that was redeemed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.catalogueitem",
                    ),
                ),
                (
                    "redemption",
                    models.ForeignKey(
                        help_text="The redemption transaction this item is part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.redemption",
                    ),
                ),
            ],
        ),
    ]
