# Generated by Django 4.2.17 on 2025-01-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_catalogueitem_reward_value_alter_catalogueitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='image',
            field=models.ImageField(upload_to='reward_images/'),
        ),
    ]
