# Generated by Django 4.2.17 on 2025-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_catalogueitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
