# Generated by Django 4.2.17 on 2025-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_catalogueitem_reward_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='reward_Terms_And_Conditions',
            field=models.TextField(default='Terms & Conditions'),
        ),
    ]
