# Generated by Django 4.2.17 on 2025-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_catalogueitem_reward_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
