# Generated by Django 4.2.17 on 2025-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_catalogueitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
