# Generated by Django 4.2.17 on 2025-01-10 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_catalogueitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
