# Generated by Django 4.2.17 on 2025-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
