# Generated by Django 4.2.17 on 2025-01-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_cart_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
    ]
