# Generated by Django 4.2.17 on 2025-01-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_remove_cart_session_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogueitem",
            old_name="reward_Terms_And_Conditions",
            new_name="reward_terms_and_conditions",
        ),
    ]
