# Generated by Django 4.2.17 on 2025-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0013_rename_reward_terms_and_conditions_catalogueitem_reward_terms_and_conditions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogueitem",
            name="image_description",
            field=models.CharField(
                default="Image description not provided",
                help_text="Provide image description for accessibility purposes.",
                max_length=255,
            ),
        ),
    ]
