# Generated by Django 4.2.17 on 2025-01-26 16:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0014_catalogueitem_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the cart was created.",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True, help_text="The date and time when the cart was updated."
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user associated with this cart.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time this item was added to the cart.",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                help_text="The cart that this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                help_text="The item that was added to the cart.",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.catalogueitem",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="The quantity of this item in the cart."
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="description",
            field=models.TextField(help_text="Detailed description of the reward."),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder",
                help_text="The image of the reward.",
                max_length=255,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="image_description",
            field=models.CharField(
                default="Image description not provided",
                help_text="Provide an image description for accessibility purposes.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="points_cost",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of points required to redeem this item.",
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="reward_name",
            field=models.CharField(
                help_text="The name of the reward must be unique.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="reward_terms_and_conditions",
            field=models.TextField(
                default="Terms & Conditions",
                help_text="Terms and conditions for redeeming this reward.",
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="reward_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The points value of the reward.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="catalogueitem",
            name="stock_quantity",
            field=models.IntegerField(
                default=0, help_text="The current stock quantity of the reward."
            ),
        ),
    ]
