# Generated by Django 4.2.17 on 2025-01-31 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_balance",
                    models.IntegerField(
                        default=0,
                        help_text="The number of points the user currently has for redemption.",
                    ),
                ),
                (
                    "join_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the user joined the platform.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The associated user account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
