# Generated by Django 4.2.17 on 2025-01-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="join_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time when the user joined the platform.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="point_balance",
            field=models.IntegerField(
                default=0,
                help_text="The number of points the user currently has for redemption.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                help_text="The associated user account.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
